from gitcommit import GitCommit
from gitrepo import GitRepository, write_object, repo_file
from gitrefs import object_find

class GitTag(GitCommit):
    fmt = b'tag'
    

def create_tag(repo:'GitRepository', name: str, ref: str, create_tag_object=False):
    # get the GitObject from the object reference
    sha = object_find(repo, ref)
    if not sha:
        return

    if create_tag_object:
        # create tag object (commit)
        tag = GitTag()
        tag.kvlm = dict()
        tag.kvlm[b'object'] = sha.encode()
        tag.kvlm[b'type'] = b'commit'
        tag.kvlm[b'tag'] = name.encode()
        # Feel free to let the user give their name!
        # Notice you can fix this after commit, read on!
        tag.kvlm[b'tagger'] = b'dumbgit <dumbgit@example.com>'
        # …and a tag message!
        tag.kvlm[None] = b"A tag generated by dumbgit, which won't let you customize the message!\n"
        tag_sha = write_object(tag, repo)
        # create reference
        ref_create(repo, "tags/" + name, tag_sha)
    else:
        # create lightweight tag (ref)
        ref_create(repo, "tags/" + name, sha)

def ref_create(repo, ref_name, sha) -> None:
    rep = repo_file(repo, "refs/" + ref_name)
    if not rep:
        return None
    with open(rep, "w") as fp:
        fp.write(sha + "\n")